/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.c_gejala;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author tauhid
 */
public class JFAddGejala extends javax.swing.JFrame {

    JFUtama utama;
    c_gejala cgejala;
    PDataGejala lis; 
    /**
     * Creates new form JFAddGejala
     */
    public JFAddGejala(PDataGejala lis, JFUtama utama) {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(getRootPane());
        this.setAlwaysOnTop(true);
        this.setTitle("Form Add Gejala");
        
        this.jtID.setVisible(false);
        this.utama=utama;
        this.lis = lis;
    }

        public JTextField getNama(){
    return jtNamaGejala;
    }
    
    public JTextArea getDes(){
    return jTDeskripsiGejala;
    }
    public JTextField getPer(){
    return jtPertanyaanGejala;
    }
    public JLabel getID(){
        return jtID;
    }
    
    public JLabel getJudul(){
        return jLabel1;
    }
    
    public JButton getButton(){
        return jBSimpan;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtPertanyaanGejala = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDeskripsiGejala = new javax.swing.JTextArea();
        jtNamaGejala = new javax.swing.JTextField();
        jtID = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jBCancel = new javax.swing.JButton();
        jBSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(350, 315));

        jPanel1.setMinimumSize(new java.awt.Dimension(260, 130));
        jPanel1.setPreferredSize(new java.awt.Dimension(305, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nama Gejala");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        jPanel1.add(jtPertanyaanGejala, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 170, -1));

        jLabel4.setText("Deskripsi Gejala");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel5.setText("Pertanyaan Gejala");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jTDeskripsiGejala.setColumns(20);
        jTDeskripsiGejala.setRows(5);
        jScrollPane1.setViewportView(jTDeskripsiGejala);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 170, -1));
        jPanel1.add(jtNamaGejala, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 170, -1));

        jtID.setText("jLabel3");
        jPanel1.add(jtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(305, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Form Tambah Gejala");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(305, 40));

        jBCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/cancel.png"))); // NOI18N
        jBCancel.setText("Batal");
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });
        jPanel3.add(jBCancel);

        jBSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/simpan.png"))); // NOI18N
        jBSimpan.setText("Simpan Gejala");
        jBSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSimpanActionPerformed(evt);
            }
        });
        jPanel3.add(jBSimpan);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jBCancelActionPerformed

    private void jBSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSimpanActionPerformed
        // TODO add your handling code here:
        if (jBSimpan.getText().equals("Simpan Gejala")){
            cgejala = new c_gejala(lis,this.utama);
            cgejala.insert(this);
            cgejala.isiTabel();
        } else {
            cgejala = new c_gejala(lis,this.utama);
            cgejala.update(this);
            cgejala.isiTabel();       
       }  
    }//GEN-LAST:event_jBSimpanActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTDeskripsiGejala;
    private javax.swing.JLabel jtID;
    private javax.swing.JTextField jtNamaGejala;
    private javax.swing.JTextField jtPertanyaanGejala;
    // End of variables declaration//GEN-END:variables
}
