/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.c_user;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.JButton;

/**
 *
 * @author tauhid
 */
public class JFAddPengguna extends javax.swing.JFrame {

    JFUtama utama;
    c_user cuser;
    PDataPengguna lis; 
    
    /**
     * Creates new form JFAddPengguna
     */
    public JFAddPengguna(PDataPengguna lis, JFUtama utama) {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(getRootPane());
        this.setAlwaysOnTop(true);
        this.setTitle("Form Add Pengguna");
        
        this.jtID.setVisible(false);
        this.utama=utama;
        this.lis = lis;
    }

    public JTextField getUser(){
    return jtUser;
    }
    
    public JPasswordField getPass(){
    return jPass;
    }
    
    public JLabel getID(){
        return jtID;
    }
    
    public JLabel getJudul(){
        return jLabel1;
    }
    
    public JButton getButton(){
        return jBSimpan;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtUser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPass = new javax.swing.JPasswordField();
        jtID = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jBCancel = new javax.swing.JButton();
        jBSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(260, 130));
        jPanel1.setPreferredSize(new java.awt.Dimension(305, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        jPanel1.add(jtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 170, -1));

        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        jPanel1.add(jPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 170, -1));

        jtID.setText("jLabel3");
        jPanel1.add(jtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(305, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Form Tambah Pengguna");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(305, 40));

        jBCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/cancel.png"))); // NOI18N
        jBCancel.setText("Batal");
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });
        jPanel3.add(jBCancel);

        jBSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/simpan.png"))); // NOI18N
        jBSimpan.setText("Simpan Pengguna");
        jBSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSimpanActionPerformed(evt);
            }
        });
        jPanel3.add(jBSimpan);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jBCancelActionPerformed

    private void jBSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSimpanActionPerformed
        // TODO add your handling code here:
        if (jBSimpan.getText().equals("Simpan Pengguna")){
            cuser = new c_user(lis,this.utama);
            cuser.insert(this);
            cuser.isiTabel();
        } else {
            cuser = new c_user(lis,this.utama);
            cuser.update(this);
            cuser.isiTabel();       
       }  
    }//GEN-LAST:event_jBSimpanActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPass;
    private javax.swing.JLabel jtID;
    private javax.swing.JTextField jtUser;
    // End of variables declaration//GEN-END:variables
}
