/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.c_analisa;
import javax.swing.JPanel;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JOptionPane;

/**
 *
 * @author tauhid
 */
public class JFAnalisa extends javax.swing.JFrame {

    /**
     * Creates new form JFAnalisa
     */
    
    c_analisa canalisa;
    JFUtama utama;
    
    public JFAnalisa() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(getRootPane());
        this.setAlwaysOnTop(true);
        this.setTitle("Form Analisa Gejala Penyakit Cabe");
        
        lidgejala.setVisible(false);
        jTable1.setVisible(false);
        jScrollPane1.setVisible(false);
        lstatus.setVisible(false);
        
        canalisa = new c_analisa();
        if (canalisa.jmlDataGejala()>0){
        LGejala.setText(canalisa.tampilkanPertanyaan(0));
        lidgejala.setText(Integer.toString(canalisa.ambilID(0)));
        canalisa.kosongkanPilihan();
        int jmlx = canalisa.jmlDataPilihan()==0 ? 1 : canalisa.jmlDataPilihan();
        linfo_pertanyaan.setText("Pertanyaan ke "+Integer.toString(jmlx)+" dari "+canalisa.jmlDataGejala());
        jBLanjut.setEnabled(true);
        jBKembali.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Data Gejala Kosong!");
            jBKembali.setEnabled(false);
            jBLanjut.setEnabled(false);
            jBDetail.setEnabled(false);
        }
        
    }

    public JButton getBUlang(){ return jBUlang; }
    public JButton getBKembali(){ return jBKembali; }
    public JButton getBLanjut(){ return jBLanjut; }
    public JButton getBDetail(){ return jBDetail; }
    
    public JLabel getLPenyakit(){ return LPenyakit; }
    public JLabel getLStatus(){ return lstatus; }
    public JLabel getLObat(){ return LObat; }
    public JTable getDataTable(){ return jTable1; }
    
    
    public JPanel getPTengah(){
    return panel_tengah;
    }
    
    public JPanel getPPenyakit(){
    return panelPenyakit;
    }
    
    public JPanel getPObat(){
    return panelObat;
    }
    
    public JPanel getPJawaban(){
    return panelJawaban;
    }
    
    public JPanel getPPertanyaan(){
    return panelPertanyaan;
    }
    
    public JPanel getPPertanyaanDanJawaban(){
    return panelPertanyaanDanJawaban;
    }
    
    public JPanel getPPenyakitObat(){
    return panelPenyakitDanObat;
    }
    
    public JButton getBSimpan(){
    return jbSimpan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel_tengah = new javax.swing.JPanel();
        panelPertanyaanDanJawaban = new javax.swing.JPanel();
        panelJawaban = new javax.swing.JPanel();
        jrYa = new javax.swing.JRadioButton();
        jrTidak = new javax.swing.JRadioButton();
        panelPertanyaan = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        LGejala = new javax.swing.JLabel();
        lidgejala = new javax.swing.JLabel();
        lstatus = new javax.swing.JLabel();
        panel_info = new javax.swing.JPanel();
        linfo_pertanyaan = new javax.swing.JLabel();
        panelPenyakitDanObat = new javax.swing.JPanel();
        panelObat = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        LObat = new javax.swing.JLabel();
        panelPenyakit = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        LPenyakit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_bawah = new javax.swing.JPanel();
        jBUlang = new javax.swing.JButton();
        jBKembali = new javax.swing.JButton();
        jBDetail = new javax.swing.JButton();
        jbSimpan = new javax.swing.JButton();
        jBLanjut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 310));

        panel_tengah.setMinimumSize(new java.awt.Dimension(260, 130));
        panel_tengah.setPreferredSize(new java.awt.Dimension(305, 100));
        panel_tengah.setLayout(new java.awt.BorderLayout());

        panelPertanyaanDanJawaban.setPreferredSize(new java.awt.Dimension(459, 200));
        panelPertanyaanDanJawaban.setLayout(new java.awt.BorderLayout());

        panelJawaban.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jawaban", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        panelJawaban.setPreferredSize(new java.awt.Dimension(459, 70));

        buttonGroup1.add(jrYa);
        jrYa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrYa.setText("Ya");
        panelJawaban.add(jrYa);

        buttonGroup1.add(jrTidak);
        jrTidak.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrTidak.setText("Tidak");
        panelJawaban.add(jrTidak);

        panelPertanyaanDanJawaban.add(panelJawaban, java.awt.BorderLayout.CENTER);

        panelPertanyaan.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pertanyaan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        panelPertanyaan.setPreferredSize(new java.awt.Dimension(22, 140));
        panelPertanyaan.setLayout(new java.awt.BorderLayout());

        LGejala.setBackground(new java.awt.Color(255, 255, 255));
        LGejala.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LGejala.setText("-");
        jScrollPane2.setViewportView(LGejala);

        panelPertanyaan.add(jScrollPane2, java.awt.BorderLayout.CENTER);
        panelPertanyaan.add(lidgejala, java.awt.BorderLayout.LINE_END);
        panelPertanyaan.add(lstatus, java.awt.BorderLayout.PAGE_END);

        panel_info.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_info.setMaximumSize(new java.awt.Dimension(300, 32767));
        panel_info.setMinimumSize(new java.awt.Dimension(300, 0));
        panel_info.setPreferredSize(new java.awt.Dimension(300, 30));

        linfo_pertanyaan.setText("Pertanyaan ke 1 dari ..");
        panel_info.add(linfo_pertanyaan);

        panelPertanyaan.add(panel_info, java.awt.BorderLayout.PAGE_END);

        panelPertanyaanDanJawaban.add(panelPertanyaan, java.awt.BorderLayout.PAGE_START);

        panel_tengah.add(panelPertanyaanDanJawaban, java.awt.BorderLayout.PAGE_END);

        panelPenyakitDanObat.setLayout(new java.awt.BorderLayout());

        panelObat.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Obat", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        panelObat.setPreferredSize(new java.awt.Dimension(459, 100));
        panelObat.setLayout(new java.awt.BorderLayout());

        LObat.setBackground(new java.awt.Color(255, 255, 255));
        LObat.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LObat.setText("Obat tidak ditemukan");
        jScrollPane6.setViewportView(LObat);

        panelObat.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        panelPenyakitDanObat.add(panelObat, java.awt.BorderLayout.CENTER);

        panelPenyakit.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Penyakit", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        panelPenyakit.setPreferredSize(new java.awt.Dimension(22, 100));
        panelPenyakit.setLayout(new java.awt.BorderLayout());

        LPenyakit.setBackground(new java.awt.Color(255, 255, 255));
        LPenyakit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LPenyakit.setText("Penyakit tidak ditemukan");
        jScrollPane4.setViewportView(LPenyakit);

        panelPenyakit.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        panelPenyakitDanObat.add(panelPenyakit, java.awt.BorderLayout.PAGE_START);

        panel_tengah.add(panelPenyakitDanObat, java.awt.BorderLayout.LINE_END);

        getContentPane().add(panel_tengah, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(305, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Form Analisa Penyakit Cabe");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        panel_bawah.setPreferredSize(new java.awt.Dimension(305, 40));

        jBUlang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/arrow_undo.png"))); // NOI18N
        jBUlang.setText("Ulang");
        jBUlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUlangActionPerformed(evt);
            }
        });
        panel_bawah.add(jBUlang);

        jBKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/arrow_left.png"))); // NOI18N
        jBKembali.setText("Kembali");
        jBKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBKembaliActionPerformed(evt);
            }
        });
        panel_bawah.add(jBKembali);

        jBDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/book_open.png"))); // NOI18N
        jBDetail.setText("Detail Pertanyaan");
        jBDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDetailActionPerformed(evt);
            }
        });
        panel_bawah.add(jBDetail);

        jbSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/page_white_acrobat.png"))); // NOI18N
        jbSimpan.setText("Cetak Hasil");
        jbSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSimpanActionPerformed(evt);
            }
        });
        panel_bawah.add(jbSimpan);

        jBLanjut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/arrow_right.png"))); // NOI18N
        jBLanjut.setText("Lanjut");
        jBLanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLanjutActionPerformed(evt);
            }
        });
        panel_bawah.add(jBLanjut);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panel_bawah.add(jScrollPane1);

        getContentPane().add(panel_bawah, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSimpanActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser("");
        int r = chooser.showSaveDialog(this);
        if (r == JFileChooser.APPROVE_OPTION){
        String dir = chooser.getSelectedFile().getAbsolutePath();
               canalisa.cetak(this,dir);
        }
    }//GEN-LAST:event_jbSimpanActionPerformed

    private void jBLanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLanjutActionPerformed
        // TODO add your handling code here:
          String pilihan = null;
       if (jrYa.isSelected()==false && jrTidak.isSelected()==false){
         JOptionPane.showMessageDialog(this, "Pilih Ya atau Tidak!");
       } else {
           // Simpan Pilihan
           if(jrYa.isSelected()){ pilihan = "1"; }else if (jrTidak.isSelected()){ pilihan = "0"; } 
           buttonGroup1.clearSelection();
           canalisa.addPilihan(lidgejala.getText(), pilihan);
           if (canalisa.jmlDataPilihan()==canalisa.jmlDataGejala()){
                 panel_tengah.remove(panelPertanyaanDanJawaban);
                 panel_tengah.add(panelPenyakitDanObat);
                 // Tentukan Penyakit, Hama dan Obat
                 canalisa.analisa(this);
                 jBDetail.setVisible(false);
                 jBLanjut.setEnabled(false);
                 jBKembali.setVisible(false);
                 jBUlang.setVisible(true);
                 panel_tengah.updateUI();
            } else {
              linfo_pertanyaan.setText("Pertanyaan ke "+Integer.toString(canalisa.jmlDataPilihan()+1)+" dari "+canalisa.jmlDataGejala()); 
              LGejala.setText(canalisa.tampilkanPertanyaan(canalisa.jmlDataPilihan()));
              lidgejala.setText(Integer.toString(canalisa.ambilID(canalisa.jmlDataPilihan())));
              getBKembali().setEnabled(true);
              jScrollPane2.updateUI();
            }
       } 
    }//GEN-LAST:event_jBLanjutActionPerformed

    private void jBKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBKembaliActionPerformed
        // TODO add your handling code here:
        canalisa.hapusPilihan(lidgejala.getText());
        int jmlx = canalisa.jmlDataPilihan()==0 ? 1 : canalisa.jmlDataPilihan();
        linfo_pertanyaan.setText("Pertanyaan ke "+Integer.toString(jmlx)+" dari "+canalisa.jmlDataGejala());
        if (canalisa.jmlDataPilihan()==0){
            jBKembali.setEnabled(false); 
        } else {
        LGejala.setText(canalisa.tampilkanPertanyaan(canalisa.jmlDataPilihan()-1));
        lidgejala.setText(Integer.toString(canalisa.ambilID(canalisa.jmlDataPilihan()-1)));
        jScrollPane2.updateUI();
        }
    }//GEN-LAST:event_jBKembaliActionPerformed

    private void jBUlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUlangActionPerformed
        // TODO add your handling code here:
        buttonGroup1.clearSelection();
        canalisa = new c_analisa();
        LGejala.setText(canalisa.tampilkanPertanyaan(0));
        lidgejala.setText(Integer.toString(canalisa.ambilID(0)));
        canalisa.kosongkanPilihan();
        getPTengah().remove(getPPenyakitObat());
        getPTengah().add(getPPertanyaanDanJawaban());
        jBLanjut.setEnabled(true);
        jBDetail.setVisible(true);
        jBKembali.setVisible(true);
        getBSimpan().setVisible(false);
        getBUlang().setVisible(false);
        getBKembali().setEnabled(false);
        LObat.setText("Obat tidak ditemukan");
        LPenyakit.setText("Penyakit tidak ditemukan");
        int jmlx = canalisa.jmlDataPilihan()==0 ? 1 : canalisa.jmlDataPilihan();
        linfo_pertanyaan.setText("Pertanyaan ke "+Integer.toString(jmlx)+" dari "+canalisa.jmlDataGejala());
        panel_tengah.updateUI();
    }//GEN-LAST:event_jBUlangActionPerformed

    private void jBDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDetailActionPerformed
        // TODO add your handling code here:
        new JFDetailPertanyaan(canalisa.jmlDataPilihan()).setVisible(true);
    }//GEN-LAST:event_jBDetailActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LGejala;
    private javax.swing.JLabel LObat;
    private javax.swing.JLabel LPenyakit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBDetail;
    private javax.swing.JButton jBKembali;
    private javax.swing.JButton jBLanjut;
    private javax.swing.JButton jBUlang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbSimpan;
    private javax.swing.JRadioButton jrTidak;
    private javax.swing.JRadioButton jrYa;
    private javax.swing.JLabel lidgejala;
    private javax.swing.JLabel linfo_pertanyaan;
    private javax.swing.JLabel lstatus;
    private javax.swing.JPanel panelJawaban;
    private javax.swing.JPanel panelObat;
    private javax.swing.JPanel panelPenyakit;
    private javax.swing.JPanel panelPenyakitDanObat;
    private javax.swing.JPanel panelPertanyaan;
    private javax.swing.JPanel panelPertanyaanDanJawaban;
    private javax.swing.JPanel panel_bawah;
    private javax.swing.JPanel panel_info;
    private javax.swing.JPanel panel_tengah;
    // End of variables declaration//GEN-END:variables
}
