/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.c_user;
import controller.c_penyakit;
import controller.c_hama;
import controller.c_obat;
import controller.c_gejala;
import controller.c_keputusan;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author tauhid
 */
public class JFUtama extends javax.swing.JFrame {

    PDataGejala dgejala = new PDataGejala(this);
    PDataPengguna dpengguna = new PDataPengguna(this);
    PDataPenyakit dpenyakit = new PDataPenyakit(this);
    PDataHama dhama = new PDataHama(this);
    PDataObat dobat = new PDataObat(this);
    PTabelKeputusan tkeputusan = new PTabelKeputusan(this);
    
    
    
    c_user cuser;
    c_penyakit cpenyakit;
    c_hama chama;
    c_obat cobat;
    c_gejala cgejala;
    c_keputusan ckeputusan;

    /**
     * Creates new form JFUtama
     */
    public JFUtama() {
        initComponents();
        //this.setResizable(false);
        this.setLocationRelativeTo(getRootPane());
        this.setTitle("Aplikasi Sistem Pakar Deteksi Penyakit Cabe");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_bawah = new javax.swing.JPanel();
        panel_aplikasi = new javax.swing.JPanel();
        label_aplikasi = new javax.swing.JLabel();
        panel_login = new javax.swing.JPanel();
        label_login = new javax.swing.JLabel();
        l_user = new javax.swing.JLabel();
        panel_address = new javax.swing.JPanel();
        label_created = new javax.swing.JLabel();
        panel_tengah = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        menu_utama = new javax.swing.JMenuBar();
        menu_data_master = new javax.swing.JMenu();
        m_data_gejala = new javax.swing.JMenuItem();
        m_data_penyakit = new javax.swing.JMenuItem();
        m_data_hama = new javax.swing.JMenuItem();
        m_data_obat = new javax.swing.JMenuItem();
        menu_keputusan = new javax.swing.JMenu();
        m_pembuatan_keputusan = new javax.swing.JMenuItem();
        m_tabel_keputusan = new javax.swing.JMenuItem();
        menu_diagnosa = new javax.swing.JMenu();
        m_mulai_analisa = new javax.swing.JMenuItem();
        menu_extra = new javax.swing.JMenu();
        m_info = new javax.swing.JMenuItem();
        m_separator = new javax.swing.JPopupMenu.Separator();
        m_datapengguna = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_bawah.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_bawah.setMaximumSize(new java.awt.Dimension(850, 32771));
        panel_bawah.setPreferredSize(new java.awt.Dimension(644, 24));
        panel_bawah.setLayout(new javax.swing.BoxLayout(panel_bawah, javax.swing.BoxLayout.LINE_AXIS));

        panel_aplikasi.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        panel_aplikasi.setMaximumSize(new java.awt.Dimension(300, 32767));
        panel_aplikasi.setMinimumSize(new java.awt.Dimension(300, 0));
        panel_aplikasi.setPreferredSize(new java.awt.Dimension(300, 16));

        label_aplikasi.setText("Sistem Pakar Deteksi Penyakit Cabe");

        javax.swing.GroupLayout panel_aplikasiLayout = new javax.swing.GroupLayout(panel_aplikasi);
        panel_aplikasi.setLayout(panel_aplikasiLayout);
        panel_aplikasiLayout.setHorizontalGroup(
            panel_aplikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_aplikasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_aplikasi)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        panel_aplikasiLayout.setVerticalGroup(
            panel_aplikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_aplikasiLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(label_aplikasi))
        );

        panel_bawah.add(panel_aplikasi);

        panel_login.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        panel_login.setMaximumSize(new java.awt.Dimension(145, 32767));
        panel_login.setMinimumSize(new java.awt.Dimension(145, 0));
        panel_login.setPreferredSize(new java.awt.Dimension(165, 16));

        label_login.setText("User Login :");

        l_user.setText("login");

        javax.swing.GroupLayout panel_loginLayout = new javax.swing.GroupLayout(panel_login);
        panel_login.setLayout(panel_loginLayout);
        panel_loginLayout.setHorizontalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(l_user)
                .addGap(60, 60, 60))
        );
        panel_loginLayout.setVerticalGroup(
            panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_loginLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addGroup(panel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_login)
                    .addComponent(l_user)))
        );

        panel_bawah.add(panel_login);

        panel_address.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        panel_address.setMaximumSize(new java.awt.Dimension(180, 32767));
        panel_address.setMinimumSize(new java.awt.Dimension(180, 0));
        panel_address.setPreferredSize(new java.awt.Dimension(350, 16));

        label_created.setText("Created By. Mahasiswa STMIK Bumigora");

        javax.swing.GroupLayout panel_addressLayout = new javax.swing.GroupLayout(panel_address);
        panel_address.setLayout(panel_addressLayout);
        panel_addressLayout.setHorizontalGroup(
            panel_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_addressLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_created)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        panel_addressLayout.setVerticalGroup(
            panel_addressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_addressLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(label_created))
        );

        panel_bawah.add(panel_address);

        getContentPane().add(panel_bawah, java.awt.BorderLayout.PAGE_END);

        panel_tengah.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        panel_tengah.setMaximumSize(new java.awt.Dimension(850, 2147483647));
        panel_tengah.setPreferredSize(new java.awt.Dimension(750, 430));
        panel_tengah.setLayout(new java.awt.BorderLayout());

        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/cabee.png"))); // NOI18N
        back.setPreferredSize(new java.awt.Dimension(800, 600));
        panel_tengah.add(back, java.awt.BorderLayout.CENTER);

        getContentPane().add(panel_tengah, java.awt.BorderLayout.CENTER);

        menu_data_master.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/DaftarPeminjaman.png"))); // NOI18N
        menu_data_master.setText("Data Master");

        m_data_gejala.setText("Data Gejala");
        m_data_gejala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_data_gejalaActionPerformed(evt);
            }
        });
        menu_data_master.add(m_data_gejala);

        m_data_penyakit.setText("Data Penyakit");
        m_data_penyakit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_data_penyakitActionPerformed(evt);
            }
        });
        menu_data_master.add(m_data_penyakit);

        m_data_hama.setText("Data Hama");
        m_data_hama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_data_hamaActionPerformed(evt);
            }
        });
        menu_data_master.add(m_data_hama);

        m_data_obat.setText("Data Obat");
        m_data_obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_data_obatActionPerformed(evt);
            }
        });
        menu_data_master.add(m_data_obat);

        menu_utama.add(menu_data_master);

        menu_keputusan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/cog_edit.png"))); // NOI18N
        menu_keputusan.setText("Keputusan");

        m_pembuatan_keputusan.setText("Pembuatan Keputusan");
        m_pembuatan_keputusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_pembuatan_keputusanActionPerformed(evt);
            }
        });
        menu_keputusan.add(m_pembuatan_keputusan);

        m_tabel_keputusan.setText("Tabel Keputusan");
        m_tabel_keputusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_tabel_keputusanActionPerformed(evt);
            }
        });
        menu_keputusan.add(m_tabel_keputusan);

        menu_utama.add(menu_keputusan);

        menu_diagnosa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/cari.png"))); // NOI18N
        menu_diagnosa.setText("Diagnosa");

        m_mulai_analisa.setText("Mulai Analisa");
        m_mulai_analisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_mulai_analisaActionPerformed(evt);
            }
        });
        menu_diagnosa.add(m_mulai_analisa);

        menu_utama.add(menu_diagnosa);

        menu_extra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/information.png"))); // NOI18N
        menu_extra.setText("Extra");

        m_info.setText("Info");
        m_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_infoActionPerformed(evt);
            }
        });
        menu_extra.add(m_info);
        menu_extra.add(m_separator);

        m_datapengguna.setText("Data Pengguna");
        m_datapengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_datapenggunaActionPerformed(evt);
            }
        });
        menu_extra.add(m_datapengguna);

        menu_utama.add(menu_extra);

        setJMenuBar(menu_utama);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_data_gejalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_data_gejalaActionPerformed
        // TODO add your handling code here:
        back.setVisible(false);
        cgejala = new c_gejala(dgejala, this);
        cgejala.isiTabel();
        dgejala.setLocation(0, 0);
        dgejala.setSize(panel_tengah.getWidth(),panel_tengah.getHeight());
        panel_tengah.remove(dobat);
        panel_tengah.remove(dhama);
        panel_tengah.remove(dpengguna);
        panel_tengah.remove(dpenyakit);
        panel_tengah.remove(tkeputusan);
        panel_tengah.add(dgejala);
        dgejala.setVisible(true);
        panel_tengah.updateUI();
    }//GEN-LAST:event_m_data_gejalaActionPerformed

    private void m_data_penyakitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_data_penyakitActionPerformed
        // TODO add your handling code here:
        back.setVisible(false);
        cpenyakit = new c_penyakit(dpenyakit, this);
        cpenyakit.isiTabel();
        dpenyakit.setLocation(0, 0);
        dpenyakit.setSize(panel_tengah.getWidth(),panel_tengah.getHeight());
        panel_tengah.remove(dobat);
        panel_tengah.remove(dpengguna);
        panel_tengah.remove(dhama);
        panel_tengah.remove(dgejala);
        panel_tengah.remove(tkeputusan);
        panel_tengah.add(dpenyakit);
        dpenyakit.setVisible(true);
        panel_tengah.updateUI();
    }//GEN-LAST:event_m_data_penyakitActionPerformed

    private void m_data_obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_data_obatActionPerformed
        // TODO add your handling code here:
        back.setVisible(false);
        cobat = new c_obat(dobat, this);
        cobat.isiTabel();
        dobat.setLocation(0, 0);
        dobat.setSize(panel_tengah.getWidth(),panel_tengah.getHeight());
        panel_tengah.remove(dgejala);
        panel_tengah.remove(dpengguna);
        panel_tengah.remove(dpenyakit);
        panel_tengah.remove(tkeputusan);
        panel_tengah.remove(dhama);
        panel_tengah.add(dobat);
        dobat.setVisible(true);
        panel_tengah.updateUI();
    }//GEN-LAST:event_m_data_obatActionPerformed

    private void m_datapenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_datapenggunaActionPerformed
        // TODO add your handling code here:
        back.setVisible(false);
        cuser = new c_user(dpengguna, this);
        cuser.isiTabel();
        dpengguna.setLocation(0, 0);
        dpengguna.setSize(panel_tengah.getWidth(),panel_tengah.getHeight());
        panel_tengah.remove(dobat);
        panel_tengah.remove(dgejala);
        panel_tengah.remove(dpenyakit);
        panel_tengah.remove(tkeputusan);
        panel_tengah.remove(dhama);
        panel_tengah.add(dpengguna);
        dpengguna.setVisible(true);
        panel_tengah.updateUI();
    }//GEN-LAST:event_m_datapenggunaActionPerformed

    private void m_tabel_keputusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_tabel_keputusanActionPerformed
        // TODO add your handling code here:
        back.setVisible(false);
        ckeputusan = new c_keputusan(tkeputusan, this);
        ckeputusan.isiTabel();
        tkeputusan.setLocation(0, 0);
        tkeputusan.setSize(panel_tengah.getWidth(),panel_tengah.getHeight());
        panel_tengah.remove(dobat);
        panel_tengah.remove(dpengguna);
        panel_tengah.remove(dpenyakit);
        panel_tengah.remove(dgejala);
        panel_tengah.remove(dhama);
        panel_tengah.add(tkeputusan);
        tkeputusan.setVisible(true);
        panel_tengah.updateUI();
    }//GEN-LAST:event_m_tabel_keputusanActionPerformed

    private void m_pembuatan_keputusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_pembuatan_keputusanActionPerformed
        // TODO add your handling code here:
        JFBuatKeputusan bAturan = new JFBuatKeputusan();
        
        bAturan.getPTengah().remove(bAturan.getPPenyakitObat());
        bAturan.getPTengah().add(bAturan.getPGejalaNilai());
           
        bAturan.getBSimpan().setVisible(false);
        bAturan.getBUlang().setVisible(false);
        bAturan.getBKembali().setEnabled(false);
        bAturan.getBKembali().setVisible(true);
        bAturan.getBDetail().setVisible(true);
        
        bAturan.setVisible(true); 
    }//GEN-LAST:event_m_pembuatan_keputusanActionPerformed

    private void m_mulai_analisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_mulai_analisaActionPerformed
        // TODO add your handling code here:
        JFAnalisa bAnalisa = new JFAnalisa();      
        bAnalisa.getPTengah().remove(bAnalisa.getPPenyakitObat());
        bAnalisa.getPTengah().add(bAnalisa.getPPertanyaanDanJawaban());
        bAnalisa.getDataTable().setVisible(false);
        bAnalisa.getBSimpan().setVisible(false);
        bAnalisa.getBUlang().setVisible(false);
        
        bAnalisa.setVisible(true);
    }//GEN-LAST:event_m_mulai_analisaActionPerformed

    private void m_data_hamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_data_hamaActionPerformed
        // TODO add your handling code here:
                back.setVisible(false);
        chama = new c_hama(dhama, this);
        chama.isiTabel();
        dhama.setLocation(0, 0);
        dhama.setSize(panel_tengah.getWidth(),panel_tengah.getHeight());
        panel_tengah.remove(dobat);
        panel_tengah.remove(dpengguna);
        panel_tengah.remove(dpenyakit);
        panel_tengah.remove(dgejala);
        panel_tengah.remove(tkeputusan);
        panel_tengah.add(dhama);
        dhama.setVisible(true);
        panel_tengah.updateUI();
    }//GEN-LAST:event_m_data_hamaActionPerformed

    private void m_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_infoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Aplikasi sistem pakar untuk mendeteksi penyakit cabe\nDibuat untuk memenuhi kebulatan studi di STMIK Bumigora Mataram\nKontak : ");
    }//GEN-LAST:event_m_infoActionPerformed

    public JLabel getBack(){
        return back;
    }
    
    public JLabel getLUser(){
        return l_user;
    }
    
    public JLabel getUser(){
        return l_user;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel l_user;
    private javax.swing.JLabel label_aplikasi;
    private javax.swing.JLabel label_created;
    private javax.swing.JLabel label_login;
    private javax.swing.JMenuItem m_data_gejala;
    private javax.swing.JMenuItem m_data_hama;
    private javax.swing.JMenuItem m_data_obat;
    private javax.swing.JMenuItem m_data_penyakit;
    private javax.swing.JMenuItem m_datapengguna;
    private javax.swing.JMenuItem m_info;
    private javax.swing.JMenuItem m_mulai_analisa;
    private javax.swing.JMenuItem m_pembuatan_keputusan;
    private javax.swing.JPopupMenu.Separator m_separator;
    private javax.swing.JMenuItem m_tabel_keputusan;
    private javax.swing.JMenu menu_data_master;
    private javax.swing.JMenu menu_diagnosa;
    private javax.swing.JMenu menu_extra;
    private javax.swing.JMenu menu_keputusan;
    private javax.swing.JMenuBar menu_utama;
    private javax.swing.JPanel panel_address;
    private javax.swing.JPanel panel_aplikasi;
    private javax.swing.JPanel panel_bawah;
    private javax.swing.JPanel panel_login;
    private javax.swing.JPanel panel_tengah;
    // End of variables declaration//GEN-END:variables
}
